import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  inactiveOverlay: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(0,0,0,0.5)' },
  topSection: { alignItems: 'center', paddingTop: 24 },
  conferenceName: {
    color: Colors.primary,
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    marginHorizontal: 16,
  },
  participantCount: { color: Colors.textSecondary, fontSize: 14, marginTop: 4 },
  timer: {
    color: Colors.primary,
    fontSize: 36,
    fontWeight: '300',
    fontVariant: ['tabular-nums'],
    marginTop: 12,
  },
  participantsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
  },
  participantsScroll: { flex: 1 },
  participantsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  participantCard: {
    width: 100,
    height: 130,
    alignItems: 'center',
    justifyContent: 'flex-start',
    margin: 8,
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingTop: 12,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  participantCardActive: { borderColor: Colors.gold },
  participantAvatarOuter: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.gold,
    marginBottom: 8,
  },
  participantAvatarText: { color: Colors.background, fontSize: 22, fontWeight: '700' },
  participantName: {
    color: Colors.textPrimary,
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 4,
    paddingHorizontal: 4,
  },
  participantStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  invitedLabel: {
    fontSize: 10,
    color: '#FFD890',
    marginTop: 2,
  },
  searchInput: {
    height: 40,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: Colors.surfaceLight,
    color: Colors.textPrimary,
    fontSize: 14,
  },
  speakingIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.success,
  },
  speakingIndicatorActive: { backgroundColor: Colors.gold },
  mutedIndicator: { opacity: 0.6 },
  mutePeerButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.surfaceLight,
  },
  controlsSection: { flexDirection: 'row', justifyContent: 'center', gap: 20, paddingBottom: 24 },
  controlButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: Colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(5, 18, 13, 0.55)',
  },
  controlButtonActive: { borderColor: Colors.primary, backgroundColor: Colors.surface },
  endCallButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: Colors.error,
    backgroundColor: Colors.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  endCallSection: { alignItems: 'center', paddingBottom: 32 },
  // AddParticipantModal
  addModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  addModalContent: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 16,
    paddingBottom: 32,
    maxHeight: '70%',
  },
  addModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  addModalTitle: { color: Colors.primary, fontSize: 18, fontWeight: '700' },
  addModalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.surfaceLight,
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  contactAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.gold,
    marginRight: 12,
  },
  contactAvatarText: { color: Colors.background, fontSize: 16, fontWeight: '700' },
  contactInfo: { flex: 1 },
  contactName: { color: Colors.textPrimary, fontSize: 15 },
  contactStatus: { color: Colors.textSecondary, fontSize: 12, marginTop: 2 },
  onlineDot: { color: Colors.success },
  offlineDot: { color: Colors.textMuted },
  emptyContactsText: {
    color: Colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: 32,
  },
});
