import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  inactiveOverlay: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(0,0,0,0.5)' },
  topSection: { alignItems: 'center' },
  contactName: { color: Colors.primary, fontSize: 28, fontWeight: '700' },
  statusText: { color: Colors.primary, fontSize: 16, marginTop: 8 },
  statusTextFailed: { color: Colors.error },
  statusTextEnded: { color: Colors.textSecondary },
  timer: {
    color: Colors.primary,
    fontSize: 48,
    fontWeight: '300',
    fontVariant: ['tabular-nums'],
    marginTop: 12,
  },
  avatarSection: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  pulseRing: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 2,
    borderColor: Colors.primary,
  },
  failedIconContainer: { width: 120, height: 120, justifyContent: 'center', alignItems: 'center' },
  avatarOuter: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.primary,
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.surface,
  },
  avatarText: { color: Colors.primary, fontSize: 48, fontWeight: '700' },
  controlsSection: { flexDirection: 'row', justifyContent: 'center', gap: 12, paddingBottom: 40 },
  controlButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: Colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(5, 18, 13, 0.55)',
  },
  controlButtonActive: { borderColor: Colors.primary, backgroundColor: Colors.surface },
  endCallSection: { alignItems: 'center' },
  endCallButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: Colors.error,
    backgroundColor: Colors.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
